{
  imports = [
    ./service-accounts.nix
    ./mealie.nix
    ./newt.nix
    ./karakeep.nix
    ./kavita.nix
    ./vaultwarden.nix
    ./navidrome.nix
    ./caddy.nix
    ./lube.nix
    ./adguard.nix
    ./immich.nix
    ./immich-public.nix
    ./uptime-kuma.nix
    ./searxng.nix
    ./obsidian.nix
    ./owntracks.nix
  ];
}
