# VM template. Fresh install onto bare metal or a Proxmox VM booted into the
# NixOS installer, partitioned by disko.
#
# 1. cp vm.tf <host>.tf
# 2. uncomment, replace HOST and the ipv4, pick the machines/ subdirectory
# 3. nix run nixpkgs#opentofu -- init && nix run nixpkgs#opentofu -- apply
# 4. rm <host>.tf before staging anything
#
# hardware-configuration.nix is generated by this run, never hand-written.

# locals {
#   HOST_ipv4 = "192.168.0.x"
# }
#
# module "deploy_HOST" {
#   source                     = "github.com/nix-community/nixos-anywhere//terraform/all-in-one"
#   nixos_system_attr          = "${local.flake}#nixosConfigurations.HOST.config.system.build.toplevel"
#   nixos_partitioner_attr     = "${local.flake}#nixosConfigurations.HOST.config.system.build.diskoScript"
#   nixos_generate_config_path = "${local.machines}/server/HOST/hardware-configuration.nix"
#   target_host                = local.HOST_ipv4
#   instance_id                = local.HOST_ipv4
#   debug_logging              = true
#   build_on_remote            = false
#   install_ssh_key            = local.ssh_key
#   deployment_ssh_key         = local.ssh_key
#
#   # LUKS hosts only, the script prints the passphrase on stdout
#   # disk_encryption_key_scripts = [
#   #   {
#   #     path   = "/tmp/disk.key"
#   #     script = "/home/gumbo/.secrets/HOST-luks.sh"
#   #   }
#   # ]
#
#   # partition and format only, no install
#   # stop_after_disko = true
# }
