background_opacity 0.95

font_family      JetBrains Mono
bold_font        JetBrains Mono Bold
italic_font      JetBrains Mono Italic
bold_italic_font JetBrains Mono Bold Italic
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0C8,U+E0CA,U+E0CC-U+E0D7,U+E200-U+E2A9,U+E300-U+E3EB,U+E5FA-U+E6B2,U+E700-U+E7C5,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font Mono
font_size 14
hide_window_decorations no
#cursor_shape underline
mouse_hide_wait -1.0
adjust_line_height 110%
initial_window_width 116c
initial_window_height 37c

### keybinds ###
map ctrl+alt+a new_tab
map ctrl+shift+s launch --location=vsplit
map ctrl+shift+d launch --location=hsplit
map ctrl+shift+q close_window
map ctrl+shift+r clear_terminal reset active
map ctrl+shift+h previous_tab
map ctrl+shift+l next_tab
### end keybinds ###

# Theme
color0 #15161e
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #7dcfff
color7 #a9b1d6
color8 #414868
color9 #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5
background #1a1b26
foreground #c0caf5
cursor #c0caf5
cursor_text_color #1a1b26
selection_background #283457
selection_foreground #c0caf5

# Tab bar
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_background #1a1b26
tab_bar_margin_height 4 0
active_tab_foreground #1a1b26
active_tab_background #e0af68
inactive_tab_foreground #a9d1de
inactive_tab_background #2b4257
