{
	"data": "ENC[AES256_GCM,data:9H4VJvJ56s/fwlN7uljHc4oEHD97wwtMORr7Xnj+pqGD8wC65w==,iv:/yGH62M6dyiBpfKKSeaYqTlsNBXVhcPFCe6p5ywVBwE=,tag:myuZlh9RQi38q/nCXPA5yQ==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHJVUlFDQSBBbUpnNFp5\nMG9BcTBsZFhtZkhLM3R4SEgxa2ZNdEZHVVRzL0VIM3U5WkxHRwpCTlF6QU1CZVN3\nVjM4a05yZW9qTW56dmQ3eTZUS0dIVVpCNmEvRXRJdVJrCi0tLSBycGJWUmViQXdK\nQ3loYWN6cnhZQ3lJcThDTTh0Q2lTVFErSVZleW5CcG9vCtSOPdyBAOy+Jr+/q7Nk\nXEalA6x9UZEuGtWcNEVJVVkHzqBORyrUHlsszVSGQMiyH43l+bgTpfU9O6Bk3DN0\nDIA=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qd84d0gr6gw0kdjztwkgk8h2k5f5477c2eng5j3d9c5qavmeylwx29fcsa5"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDVkNDNGQSBBM1JDdEVo\nZFl3ZEZnTDVGR0NhWXlZMXRMa1ludS9qSE5TTWVoRXJHenUxUgowZTUzbHhPc2pF\nUkRqYXhEQnlpTGQ1c2g2Z1lacDZoMXdoOFh5c1pERUhRCi0tLSB0MG5ZK2tiNUhL\ndjMzRTBrOWxCM21XZjZjUUF3cGJwWC9zSmo5VGg5RFhvCkQu5h7GkKIRcpgZTlPb\nypBrwtBY9oUMHDqGwf4AMIMx2jnxwOr/VduApkSRgqls+wjy+MuQhcF6cLk+yCux\nZYk=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qvkcdmncywzgx4vvhmel4zv8cx3zzgmyx2rzvn9w6u8d95k3qatzqcrm7kj"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG90MTY4QSBBbVg2OTFR\nclNKZWFZdG9aZFNKRkxNWWkzZ1FKeHRaTHEzVm56dXlLWGxFaApvc01KNndPMy9U\nWkpZV1FVVkJYejcwMzVucXJXSnloM1dtdGlFL1h3UktVCi0tLSBXSytERGd5TUF6\nbEluTkcyakNlOS9JcW5zUmhRSXVQV0lscXhVNnNqc1dVCrGC6CaG9zwzlQTbZzLn\ngSvzKPqFaszhgOrMrdUhurKdqZ/ayfk/AOKVaKLYDPyjyAXlhfk/4p6NhpRtHxiz\noFg=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qdpmtxksz55pzfaju625atdyhtksvsclmxhuqqux6s352wq43ge0cg0cw26"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcmZvakxhS0F6eHhRNzZy\ncDNIWnR3a24zMnAvSzZmNUcvQndiNXdCd1JZCkpiVlZXVDB2VlJKOHg0aXp4SStP\naHdXZXdCYm1udTdQWTE2V2poUElIaUEKLS0tIE5zYU5oTy9qRVFFUTNrcmNjWGpi\nZHpBM05RZ2RadXY3N1dZdDl1aDVLVDAKgbNVKQTC/XEiLvXtWmUZ5Ti1ZV62WcOS\ns+uT5FIY0MHI79Q+liSyD/nQ1zc6lnERHTDKH6HPlpU+Q9OhJi01Eg==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age12e0zcqpclf8gh0wu39alq3ux9u0rpu5tc4qtlqvpldkd79ew0p2smnklp0"
			}
		],
		"lastmodified": "2026-07-19T20:38:20Z",
		"mac": "ENC[AES256_GCM,data:d2js4jaa9ioufBwlOylM2bWFSmdytO1tQPrc+hL6TGlxM09lq98n/UGIZKS8tetKH7BL9vJci3T5vxrceTaLxCz8WVfF401dME9Nxcjc2leUCQILuvNYCSJrdnsbXagnaQTZvA7Awy60VqiAIgP8/hqIvPtRtaVrOVxkGiAF7zE=,iv:R+Q33iOb/piOuJnlFbSRu/QFa1Lk9AE/KlkKJXiEhD8=,tag:TgENwmJFnJmVAp/ImUld5g==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.13.2"
	}
}
