{
	"data": "ENC[AES256_GCM,data:6TcNcPlqx6IS8PY3vRxdAgOBXrGi752z4As1G8SjTSYGty9rVQ==,iv:090EMOKUAIYyDt/KrrjPXYwZYsr/OBF7R23mRGMZFgo=,tag:1GaUzyEPx/x9XczgYOOFXg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHJVUlFDQSBBeGJyQXNi\nMlM5bTdJS1JDM2t2emROWFkxNk9GZ1pJRXJpRnhYTFNmU05ZcAp0SlZKa3YyTXZT\nODFwU0RYQTltYzdEQm4rbXVtN09GMURmNmJuVGFaVnNVCi0tLSBFcU8zYmdlREZX\nWnVGK1hyQjRDcWtpTTQ2eFpaUmFnWVFrM2hkSlpudHdnCn8AQOsNiPJMz1pUAM+C\nWi9HrB7EagbVWLPgNd7UxrFdDcVvxZituMsP5vpjdVf1bpXmwDCNJQFqdE8j1p+Z\nReo=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qd84d0gr6gw0kdjztwkgk8h2k5f5477c2eng5j3d9c5qavmeylwx29fcsa5"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDVkNDNGQSBBc0VJOXk4\nU244cERLNkxvMlRNWVhMSE1ua0lKTWFscGpFUnl2Q0JZL2xqcwp0L01vM2xhWGZz\ndHhGeFZMdVdaZ1JqSkxiQzZTRW5lUE9DYnRLSTd5bkpvCi0tLSAwcGlVcitLeXZG\nUzRtSXpCdXhZM2hTVjQ0NjNFZGZMMEYwR3R5VllwMm84CgTsvdM7q+pzaku4VQWr\nmEf1D+mKAEhGw3YP6GVurDsEKpCHhPumCFZ9SATkp3pMt2lVBigQo+E3PFdaZlR6\nqFU=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qvkcdmncywzgx4vvhmel4zv8cx3zzgmyx2rzvn9w6u8d95k3qatzqcrm7kj"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG90MTY4QSBBNEtuWkM5\nd2NjTTlIbUN3M1d1L2lMOGxSc2JRejhKSjZPTFNWcEFrUW1YMApzUEJud2kzQUxy\na1BydWVYTnhMV2JiUWwzcHhRWUkrejRuZWhNaUd1MEt3Ci0tLSBmdElsVnJkamxl\nTitoR1JrSFlqZXQvTmcvMW5WMUhYcElZYytqV1phbWdZCu/optfX9NCMoAc64ls9\nME/8LNuOaKs8G4Wlgfzb3vYE4S0eRSPJn8JJEgZ8Bk10/Ujl3H9JpDTw4YsiQYAy\nXSQ=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qdpmtxksz55pzfaju625atdyhtksvsclmxhuqqux6s352wq43ge0cg0cw26"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTU5QdCtSTVNaWVlZenZz\nbUVTd21FM0NKUVozZjF6MmVqWWsrRERub1hZCjRCMjZ6aHNBcEc1UDRFbmkrQXMv\nd2FBWlA0YU5uTVVzanpScHhWQ2tBTW8KLS0tIHRyUitkdFNlYTVJQ3JBT3NBSHdi\nNGxMbUhMRk1QVDlVSmoySGcrZ0dFRlEKsta59b+hba4+2GDug4VZFysAY/mXkqot\n0m8tWZV8eQXC/F4iuMifF9a7l2To1zE08HS7d8SqIwnT/CkEi8UTXA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age18apjd378vwlnts64wznwh9lknndacxakjdwl0ldstplzkpwspf7qw77w3p"
			}
		],
		"lastmodified": "2026-07-19T20:38:20Z",
		"mac": "ENC[AES256_GCM,data:NRXEY1ZPWR2Ae+um+p+fdWbYNd7VQ3VmiNchN0O4s4ulFeBzBKYB3vU7KoBkEYnFww1A+kiPBFeHuut+n14d5UckuxnEyJN78iji/Ct53F/oVoTEi5wswU/CT4hqlQsYzYyf6+aOgn/Ghgur8nSix1+7NvmmupsX4mILto+Ax2M=,iv:78dS7PkD+O/wHRNGxxw+CrcNyU+wi5J7kYzZWQqCaSs=,tag:UJqNnJxIuPxDifuqn3QY0w==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.13.2"
	}
}
