{
	"data": "ENC[AES256_GCM,data:fna8a78ZX8I4UgR6bH5YPzH2R+n9Wkw7Mtmk/yuqWggmNsqHmA==,iv:WHeI9ZYs7pDSq34NcPeNfM3Qp3kVb0Gwd2HR8EmsuMY=,tag:8sYvZ3JZEdkiI5NevXx+Hg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHJVUlFDQSBBb0JSQm8w\nTi9nSlpqc2ZjdElWTGhPckRXeUw4cmVZb3ViUVR4d01WZHhtTAp2cGZ1RVZyVDBX\nc3dCWVpabEF2bEd1a3lEK2RkVmEzNUxLMkh2dzJmM013Ci0tLSBKd3Q4Q0ZSS291\naFlHWnQraFNkRFZabzBvUUZtUHhvSUIwRmpsb0xpdkt3CpWG7OkIFrZAlXjP6Piy\n1VH8fpsnjrREMcUkage6DbM5jYs+EUVmHGCWYNi1PmWnm/1EZ9gr3Tl16uP8zA6n\n1y4=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qd84d0gr6gw0kdjztwkgk8h2k5f5477c2eng5j3d9c5qavmeylwx29fcsa5"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDVkNDNGQSBBOTBvbmFN\nOGhqQjNPNGtJenVlQ0FPM3M2Y29jekRpTGpMQVg1ZXdJWWhEWQo5TDhzeGxLejU1\nVTN2dEoxZkUwM21hVGRLOTBpRzBRUlAzbWVQcTJsRVd3Ci0tLSBGSUwybkNyUS9v\nRkc3S1BCbzI0TXdMZTlkMUZ4cFJxWEZWMWFXSEtHSFBrCn0DD2xG3m1TD5+zlODf\nAvVyhSB3HUgxFRrUqw9adMim+JoX8kSCVmDdoHdzlycvH0FNSeHumkCDSuwU1Cj7\nkeg=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qvkcdmncywzgx4vvhmel4zv8cx3zzgmyx2rzvn9w6u8d95k3qatzqcrm7kj"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG90MTY4QSBBMER0d2JP\nTFI1Wk4wVG9ua1p5VnpIaHNCdU52S3dhOW92K1N0S0V3Q3lTcwp3M3BYR0xJMDlD\nZ1Z4WnhwdnRTN0QyYStsUTI4bklvWkFxc1JQT0F2eDF3Ci0tLSA5V0VTQkdYWnpO\nbnlvTTFzaWt2M1VETkt0MGhpSnhGcEFUQ2R0NG5rKyt3CslfHVCtU4mvYo2yvROe\nEIg65TKNAoVjndav50EJH3zPo6PqucZn1eX/oRF0NdvhyHrrziHxI2GQ4BTSxK5A\nZD0=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qdpmtxksz55pzfaju625atdyhtksvsclmxhuqqux6s352wq43ge0cg0cw26"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WUwzL1IzdUpZWms5cS9W\nUTErUkRtb3k1MjV4S1JURGF5dXY0Qi9CbEdVCmRJa3lvcGlqZDZ6WkRXczcwSXh2\nSkdOOWlNd0V4SmgvbHRET2ZiUzJad3cKLS0tIExMdVFrTk9pM0hTNDExcFhoUmlq\neUIwMlRRWVBpbGxLRUtvQjBObGpwWG8K/qmihZ7F6tjBQjK03Etk9VCowceFqImZ\nkIqTLEQGsOISUCuF/nXHxw2vFK0rzb3juDry94GoNDHuYpbt5OzH4w==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1n7luzkfg2t0a44uqsz97f2gvjhk3fys908skpd8uzkg98ah3fyashcc5ms"
			}
		],
		"lastmodified": "2026-07-19T20:38:20Z",
		"mac": "ENC[AES256_GCM,data:maAcOl9SpbTA+cAC/PzLAbgpI4OiCVPnUYNYHZawGOUNxvVaYld1QUyFXpbam9XH9S1XGselbZVLPSj2l8fUgl/pxBYze6GgqiedsPiwmXWqRbhzp/OKxvduk+9m5TgwZuo04szp+d9nFFrVWjtCFKR9IxhdWLE+iXknEnlVDDQ=,iv:68Dup6ac0LItzaqkWwS7YCBGersbsaJuKpjlmVk+Chw=,tag:uAkWFLLhSQe5HFSM9CkDwA==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.13.2"
	}
}
