{
	"data": "ENC[AES256_GCM,data:ADVP/sUFPN5JRE0qjZds0geq4UhpHtfpn3ZXTGjCPxgBFEKchA8XjCreHuohi+tEJdzIhAuHRlj2vOhCiPGi+ydwP9mK5Z71WCNDDuNYJAjjmiiRWF9Xe6/QQE58Jo7wtSqI0fDbPxUee/78/zreEsMXfNqLVIkH+OzUc96yPbu2rKkrY32FLCE/EAbWG2VME63otmkYLqle3yug7AER/u5h+HNNAOeFUbaqLgNEO/ffynXmZY9OFDHURRjvJnUfPjTeZDeWNF5ebZev68jPcMPmKWPR5UA25r/YkCLh611pLQsFMWYtiFp0Ax75lJEE6WwmhaxVWv8HA0n1K+RdFrZrWTGj2DEVDmLEQlUdBc72sbbAE0ui2bWTviwtC4TxLdd0lYLt/MWpj6i2xn/UtFd07e4y26lVSJEIF5UAJXar6KD1nbBIKrOg7x1sZVt/pY7WHDMnfDG9eTk=,iv:Oz34EyOjyBPAv8P+xv0k6sDCmjPjRpe0dqrkrzI4uqQ=,tag:JtG8xEStXsvBkUfP25mSHw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHJVUlFDQSBBbUtLeEcw\nZ21neCtWR3ZHZzBQSnhjRjBGSlFtVkEzaTZybC9oZWlhTWtGRApKSko3bnArQTQ3\nNUdVVnFVQ1pLa0VvRGxTMmRyM2xYOXhjRTdyb2V5WHE4Ci0tLSBId2EwNEx6ZUE5\nRVIzQ3dIZStiVXBDREZNd2MvQUdhV0gwZlVHSVJQZ293CsnXzT+R4h0Aq/mbUumI\nr2ZUoELu6g4aZQepEQUHC7zg/gl7oX0yS6Wc5XKdBqJ5BYnA8Ss5dNxCQ9U3zIWT\nBuc=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qd84d0gr6gw0kdjztwkgk8h2k5f5477c2eng5j3d9c5qavmeylwx29fcsa5"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDVkNDNGQSBBaG5RZURx\nRk5sbzV3cUpjY2lVUE5nTzJScWQ5ZXZ0Q1QyNDQxUkZlT0pYUgpjaFNjWkVwNmxO\nNXg0VDNEeGk4dTBKcVhBVUxBeVJ2ZTR0YVV1ZXZyd25rCi0tLSBsR3ZZeEU2NS8x\nRFVkbEV5R3Z1RFhDZVNWeWJ6U21RSVRxOTFKam9DaXY0Ct7iaqLrh4kXGVw6n3Ft\n1CmYxR4F/WjtwxE21nM89URz4hoay6zEK21aCqNcqDMO3OrOWVnvdxh9zbaEh2Su\nvog=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qvkcdmncywzgx4vvhmel4zv8cx3zzgmyx2rzvn9w6u8d95k3qatzqcrm7kj"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG90MTY4QSBBbDg3YzFN\nakhKdlMxRlZwbHZJSFVZQlhSUzRzYUU0eTAvbEplanF6MXNGRApraWZwSUp1Rzc3\nUUtrMmYyZTJGMjhWTlpudFMrR2RZL3FDSVBPTGdTVS8wCi0tLSBWcXJubXFiallB\nZzNOcmorMWFZK2hTS25wM2M5aXJFTDcrMkNBQlBjeVZjChoOQZPZMM3cUlE2QZbv\nwn/w4Eg9Sz0fwmcf+nJXEdc1IuAkGqP2E++m7t5A1mBzVfCJen44L1NEny7tFuND\neOI=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qdpmtxksz55pzfaju625atdyhtksvsclmxhuqqux6s352wq43ge0cg0cw26"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcmprRjNoVm5pWnVmclRV\nVFNOMmIwNHAzWU5ZWjFzNnM3RE5nWmhtRFhBCjBZSk1PNFZqZnExV0dqdHdnYWNV\nMWM5VlA0YXQ4SWRKTlVJU1J2MnptWWcKLS0tIEVpbkp1eW51ZEJUdVR1MFJvdWNx\ndXZLYmhpZkZGSU5tSWR4R2ZzL0czbFkKL2mdIBzbH7ukBQyp30RY8k2/x9A1BqRd\nMofAeJPQJ5K3GxuGYkfEKPT6UgjJOjU/VOye1/sLiynnuKorNEQs9A==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1dtahzr3uqenkj4gt6p8ranheglmh9nhl9tasyjj8ezm9xzqpx9dqtvaups"
			}
		],
		"lastmodified": "2026-07-26T02:38:01Z",
		"mac": "ENC[AES256_GCM,data:8oJH9Cse8Vsjm3Ei3iv/XsKnWRSKtuJHmXfsqr3/foWTUwrFiiMnjYtbOUkQCkdZ/aPIk23vRTBefqwEJ7ji8UrbkqmFHxDiUr3VZ+F9p9+e05rZ7uJ8gwSm3AQWoNW+ia2NPpqBaTYpzJlk8uIUcBJuLqoUB1brW5Wl3hN5f7I=,iv:digJhx+ak+5ZvFs36BPdTnHhUznO9ble1uRELwkjcPM=,tag:64+B2xmFn5YaLErY0jykgw==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.13.3"
	}
}
