{
	"data": "ENC[AES256_GCM,data:9OHxBb/9j0o3kK1qEa3u2zSiCdU5N5K4jJU4Pgpfy3OIvPAeHLZrwAEfN2QEUy0QxI22/KSt5MjmrlA9H/APDx1da22DdYswWF0Pb/YCemAhDNj+6q7aOTD9gipPMmrVwOvIgc6/H562BNrh37mvQFhVxUKZXCOT/2yj5CX2N0tYAQz2Ghn/hMR3SZ/4PwZQ0+j3+hD4fZ8xSGRReFLbNtwB3ZzfRZ8iJ7Dc2BmV6NHTafwnjpGYMUWLPPxZCRv8DbZQt2ufpmJH6UdDQoOwkqpCzQFj4mywjTKJhc7Dw0Cf2O66f1hNrgIeOwrSWKu6fKFcfYGM2T9NJ/cRe+9hD5zjYaUaKUHJTsQA9AfA5vWxuYvB92N9e2aeRBK/wURR5ECUpiMLFg+0yXD0yIPMW5CERS4hYyZW+FRMLedYoJaEcoXc1himh+imQmIyur93XuKw5y4J75jfCSFUmDaHerAN9AZwK37XO0ELm29PGhOEsdGWxlHZPtdCam3ipvgaGsq7lu5Cto9AqEyVvAKEidtVI0s+9yZPHS2kCqkTNTYttesktXd6U+yp4MYfdvUXgaEYX2XPtKkBHoKedD1N0q1r2PkC05zBp2u5EBAXWCvoXFvFpXOnfGI=,iv:GfL4HNgUPGB2JkZp5tVg820yx21yXB8TxrIKvqP7mDE=,tag:Pm4FIrpjdhP2wdUUrJikug==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHJVUlFDQSBBaFFPVmk2\nUzZJQWpjRzB1UTk5T05iMW9xNDhEYzdWYXF6TjJ4VlJBYzNNTQpBL0w1SzZDcnpZ\nbzY4cTdEWDVzTURQSmQva0tlOGlyMnErLzFZYVVBc01FCi0tLSA2ekR4VW9rd1Z5\nSlRpdG8vYW5mQk4vaUJOd3RNQnlBY3RocmxDOHVvQzc4CrOe5eVWtgMXB3VrLQXW\nsTRLhc5E5nfVlEmKFb9NtmCDLUNcidseLd4PWlpPyK2SW5f0RVx8Hjuga1aU2Rbz\n/vY=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qd84d0gr6gw0kdjztwkgk8h2k5f5477c2eng5j3d9c5qavmeylwx29fcsa5"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDVkNDNGQSBBeDBpRzRw\nMzMzQ1kvVTk2QUhDdS9MSEJBS3drZk10U3d2WnpOQlBxTWE3NwpqZCt0Q01ZYitx\nRkh1bTF4M242Z1FONWhtVHhkOGNHeHgrRll5Zk9HREw0Ci0tLSBiZDIvRWwrNm9I\ncEZJZTUxZFV3Z1hXNVVUOWNGS0NoUHVMVVV2RVZvZ3NNCmtLNp/8BWBKpS3gbBpV\nFymmuV6O6FkhXRZE+viuBbL9FbQNk7F6312iypNqLp0bhX+wkVXcC7o3oGlgFRUW\nEEA=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qvkcdmncywzgx4vvhmel4zv8cx3zzgmyx2rzvn9w6u8d95k3qatzqcrm7kj"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG90MTY4QSBBNEFsUHFR\nTjZzc0V4cjFyTUhKVEVRQnphWTFHL3NmcjAxSmRuYjQzeUUxNwpLdXZFelJJZGt1\nZUMxZm1pWkV0b3JvT2s3bU9qZFNvNHlUREplRTM0M3NvCi0tLSBHMFFkQ3QrS3F5\nK3BmTHI2ZjRRYTcvQVU0VVNzWWsvYWVDYzFmNXFTNzVjCslTJs7h9yYFVkHwU95o\nAKXh6lATFysZTGekpTc5TVQimueStv90HLipsYwuo50Qu4jzgdUsW1/FKDbB6c/G\n7M8=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qdpmtxksz55pzfaju625atdyhtksvsclmxhuqqux6s352wq43ge0cg0cw26"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRGZRWEh0a0FsYWpzQ29N\ndWVyN1hxc0dxSWJWTVdqSGYzYnQzYXRqT21vClFTbU80bi94UzcwRFBLM2gwUFBF\nTFlqeXJPMVljd0tHNEZlWUJKaDF2NWMKLS0tIDNnUHRuSk8ydm00VXhJMmhWNkhX\nenFRUUZiWVZmMzRSdjZVWEFuNVJRRE0K/66j+HNGl3nVdY0SeNHKbIUQk7AB/Vtz\ni3Ks/PQJiNL+kN+9pxYikCGP1n/sR8N7Fy7fEAJyCXfDGGHlwzAI8w==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1dtahzr3uqenkj4gt6p8ranheglmh9nhl9tasyjj8ezm9xzqpx9dqtvaups"
			}
		],
		"lastmodified": "2026-07-31T01:52:53Z",
		"mac": "ENC[AES256_GCM,data:z4zhDjWvchAczXEneZxQB6/VGrvhgv7sNa54W4oiR36YKHUUeoqnVGseeoF46bQTghVGQM0tM0QmMKlT4oUVailzSA4wrwGzb7ee+Y0RlK0nGoluuLQq2QRQiGsKrczyquzp6ysCdNYA7OpzK4OvQk0V4ssRpDLs0YrxeE1o+e4=,iv:CyP+6p4OOMwBX5nwT+LsTC+L7199Wq0Sxazt/qewNCQ=,tag:tPmibHd5Gj5Ih2scaJ+KNw==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.13.3"
	}
}
