{
	"data": "ENC[AES256_GCM,data:WL8tL9G844nRpqEw4hd0j4FkFW8+jGy8jvN+7o4gB+5SpdTve9evYFF3SMKrsJjFGqQ5F+OYUxJs+yZlzA0q+VZrWruDbdoAR5ukBUiwOVK29YvMdD9sUHOqghkB+Mw53zUHklbyRKhddbiORbQc074nM8xMVYMBB5cPmjlR88+mvccMwZyBK7FfOkj+CeyUssvKf5olPBWqFig6ypYqTkncIBvAU5mrfLmLLrUlGqGqhYyqHvDLQRo6YB2typzzQ3BDvLxHVRiBzgZ0yVPiP6JchvAFPIR5GRVZj2jtge2GXUi7bKXOA/GMjwjbdUcTvXDjFTUmRvjEBfnR6UO0LkAawBDjCDhDgx00fAFW5WuG3Bj1BDyElQMq+FbUgwXeOBKqE7cBNI4AfazmUg==,iv:BA59gMVt4aiJlQgwQt3gcd9jrXoPY9JIcoB2e87fO0I=,tag:UKQjz3SGjcFfZU0eWXz3NQ==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHJVUlFDQSBBcDV5Tmtm\nQ3F5OFZPSlIvb3YrdXNvakQvSkFqM2tLUnNGTGF4Rk5LSVJyVwpUbWEybjMxdjdK\nZ0NsQVZZaDhCSUJGbmxKNFhRU3RnVlEwVWdoZXB5Z2I0Ci0tLSBrM2dGbE96a0po\nc0F1VnNRY01EN1lkeGZBcWFLWGZiUEZaSEFsZ0UwdEI0ChehMNwvQsE6c/GCeapB\nMm+Wp9HGpt8BsNDfpHY6P623xJMvkCIamvUQTeSqb10Yeon2IwNwFqJEsjtr2u7d\nyiA=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qd84d0gr6gw0kdjztwkgk8h2k5f5477c2eng5j3d9c5qavmeylwx29fcsa5"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDVkNDNGQSBBL2FZa0Qx\ndG1rcCsvRGx5ZWwzYURPYnJ6bEtmSkUxY1FLUGsvWjFOeVE5UgpoTXZKV3RnMnR2\nZEJ2dlk1eWJITnN4Ty8wQTZ6U05FRDhTNUtVQmJuUXF3Ci0tLSBkZWZpRXZKRE41\nV0dhSkp1bEQ4MDhmUmNyMkJBY0Z6c2FwOWVuSUlLRFBnCoAk+Z8MXIb96fnFTeqM\nwte9pXGTFqDpcxnABBCTKL55DZ/15CJraaA9wmzJaNG9i4JIjR63BXd6Phbm0UAH\n+eg=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qvkcdmncywzgx4vvhmel4zv8cx3zzgmyx2rzvn9w6u8d95k3qatzqcrm7kj"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG90MTY4QSBBb24vc1NN\nS28zTEphT2RVbko4ck0rOU9zeDRwZFlzVnFwSHljVDJaZ0pnUApwamdRbWlqY0dI\nWTI1cHVzdVU0LzNtT0tYN29keXFTamhuUitOeTR4c0R3Ci0tLSBJczJzMnp3TG5P\nMVdhNzlaMUNscmZTUWRkTjYyTVRTSGxHZVMwSGtZNVZrCkgv7XQDP/ZlbSbJ/iN4\nHKsQj866ogZiXohgAWj6LvWP1Phjykl44+7FhBdUsLaf11ZMKSnv4w3GFwAdRpxy\nCE4=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qdpmtxksz55pzfaju625atdyhtksvsclmxhuqqux6s352wq43ge0cg0cw26"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MkdhWWhuZGtCang3TUhU\nVlUxMExDMDhCUEVGbTYvbVR3UUdudHB0RVZjCjF0UDBhbGVRVjVrcXZLWHUydWpT\nZ0JaRXFrM2lXUEFFWVY4MWYrSGdzZVEKLS0tIDkzMExqRmw3OHorU0U5NjhWNVZD\nOXRNUWswWEZVSkV5OGR5L1RQWTBpdVUK35UIWxdn6VVYfBROEy/89budFRWBTTd0\nohdyO0gQGORfzS0KsBWFFttM+HRiac6rKBrkSZ66Gch4qXS57L0D7Q==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1dtahzr3uqenkj4gt6p8ranheglmh9nhl9tasyjj8ezm9xzqpx9dqtvaups"
			}
		],
		"lastmodified": "2026-08-03T23:30:59Z",
		"mac": "ENC[AES256_GCM,data:b2RYQG9PX4+ElBQBmNxTsh0J+HFP9tbYD12zb/6YI6rWKSU6Cs0BjoJ2Tmh5NPdoVcmi+xhotOD/KO5kU2yZNnh0p5m7Q7KIfrNRZLbTKwF//9H+puOE5hZaZlocJnj+La5NDFjqr2rJfXBqrRbXnCBKRbNgKpIGz3QwgOGUplk=,iv:ZCRWU5rgfZVAZletbwxUxWsS4sAfaI2iJBAY8zQKK+4=,tag:X6W+7c8KmzyOEtbUFOdDFA==,type:str]",
		"version": "3.13.3"
	}
}
