{
	"data": "ENC[AES256_GCM,data:h6L5VAvmwirvLne/UvoTPFD/nE/2DceUx7sWq1u3n4FVnsc9M8QlNe8iRnznCnCXMpxa+MSwErTFqhPKPSI9ulLPfg4HSb77lvYuLoKGRBVDGxacEDMDgB9EubuqNJSwoOWDX1Pxt01qpZjuvU8Y4vc50HJUZPjpuU7U0H98LtNsxBcnAeyHGNqjQfzjPC7VcOXoTiEiFpleieZZ47m1DErsc9FIRUX04/lt2APUyR+5Oc9gsQ6N5caGoBQocOXLhgqiVwSQMCgClZPJTIilckoPJ0Y6P7LHNUW1h5Bk//GAB0SSCWycJ49/vYjMEIFQ+It8e2MxiVtwY77KM6+ysknGxHPXJpHWhV4+sm9Cgp/H3hJZuylEfxJGgZJrRt79uYuVmjkFIENcvQBJCwpWYS7oLTJSamj/,iv:E4EQ2QpsEV6HwYDexdKlEbby8dpWo2Ud3RpE5L+F+/Q=,tag:anzJPqm8mxN9yHLVkO1LPw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHJVUlFDQSBBcDV5Tmtm\nQ3F5OFZPSlIvb3YrdXNvakQvSkFqM2tLUnNGTGF4Rk5LSVJyVwpUbWEybjMxdjdK\nZ0NsQVZZaDhCSUJGbmxKNFhRU3RnVlEwVWdoZXB5Z2I0Ci0tLSBrM2dGbE96a0po\nc0F1VnNRY01EN1lkeGZBcWFLWGZiUEZaSEFsZ0UwdEI0ChehMNwvQsE6c/GCeapB\nMm+Wp9HGpt8BsNDfpHY6P623xJMvkCIamvUQTeSqb10Yeon2IwNwFqJEsjtr2u7d\nyiA=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qd84d0gr6gw0kdjztwkgk8h2k5f5477c2eng5j3d9c5qavmeylwx29fcsa5"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDVkNDNGQSBBL2FZa0Qx\ndG1rcCsvRGx5ZWwzYURPYnJ6bEtmSkUxY1FLUGsvWjFOeVE5UgpoTXZKV3RnMnR2\nZEJ2dlk1eWJITnN4Ty8wQTZ6U05FRDhTNUtVQmJuUXF3Ci0tLSBkZWZpRXZKRE41\nV0dhSkp1bEQ4MDhmUmNyMkJBY0Z6c2FwOWVuSUlLRFBnCoAk+Z8MXIb96fnFTeqM\nwte9pXGTFqDpcxnABBCTKL55DZ/15CJraaA9wmzJaNG9i4JIjR63BXd6Phbm0UAH\n+eg=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qvkcdmncywzgx4vvhmel4zv8cx3zzgmyx2rzvn9w6u8d95k3qatzqcrm7kj"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG90MTY4QSBBb24vc1NN\nS28zTEphT2RVbko4ck0rOU9zeDRwZFlzVnFwSHljVDJaZ0pnUApwamdRbWlqY0dI\nWTI1cHVzdVU0LzNtT0tYN29keXFTamhuUitOeTR4c0R3Ci0tLSBJczJzMnp3TG5P\nMVdhNzlaMUNscmZTUWRkTjYyTVRTSGxHZVMwSGtZNVZrCkgv7XQDP/ZlbSbJ/iN4\nHKsQj866ogZiXohgAWj6LvWP1Phjykl44+7FhBdUsLaf11ZMKSnv4w3GFwAdRpxy\nCE4=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qdpmtxksz55pzfaju625atdyhtksvsclmxhuqqux6s352wq43ge0cg0cw26"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MkdhWWhuZGtCang3TUhU\nVlUxMExDMDhCUEVGbTYvbVR3UUdudHB0RVZjCjF0UDBhbGVRVjVrcXZLWHUydWpT\nZ0JaRXFrM2lXUEFFWVY4MWYrSGdzZVEKLS0tIDkzMExqRmw3OHorU0U5NjhWNVZD\nOXRNUWswWEZVSkV5OGR5L1RQWTBpdVUK35UIWxdn6VVYfBROEy/89budFRWBTTd0\nohdyO0gQGORfzS0KsBWFFttM+HRiac6rKBrkSZ66Gch4qXS57L0D7Q==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1dtahzr3uqenkj4gt6p8ranheglmh9nhl9tasyjj8ezm9xzqpx9dqtvaups"
			}
		],
		"lastmodified": "2026-08-22T16:14:14Z",
		"mac": "ENC[AES256_GCM,data:BB7oqLmVCN1bLNgEnM5rfd3bSfETmibgR0kBNsbYPHmz5WT4WYVbP4wK+JvLw5fM2DphVovLOwZyvQEOGHDSDU7HL2Ti2AfF6DbHPq/rEWpn55FQ+QyF2hYtUJJLekV2VMkJKuuwwNUxiIfhCy61Nb3ow1QwvJ/n6yL1qZj1/ls=,iv:eYArAg/6jhhIA+LzPWFSfasCih8d65eObY9mZhCc/6Q=,tag:V/mQtICvVIkzPcMW4WpqWQ==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.13.3"
	}
}
