{
	"data": "ENC[AES256_GCM,data:pjX11ECsTHtZZ1RszzPpKX66qwXNDvHwKHNXtIXUkpgo306qPQ==,iv:HAwoeaxpZKyY7mArbEIyVSvOMfEkOdvfM7rpPmQPKPE=,tag:kHJ3lYNhvqf7ZHWAegp8Tg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHJVUlFDQSBBZ1NHbjAz\nSDYyTU5ETGYvaVcwVEdVNVBiYzFKSnNRQXR6em5zY2x5T2c5ZgoxanRZYUt5ZkZP\nUms0YmpSYXIxZU5qcVJkNnpOdXZ2UDJaRzRNTUZrSTU4Ci0tLSBGeHAvaDhLSFM3\nbnh2dEpsa3g5Y01CWnNBWjdrdThPQVlMblN1WWpWWmNnCi8lyt3ORMCmsS2FAvTN\ndAS6Uv5VjPX19jEyJV5Hc/xqrmLfek5MuhAe2+jfq1tkm6Pz/ukNfDxTmNDXAFh4\nEzQ=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qd84d0gr6gw0kdjztwkgk8h2k5f5477c2eng5j3d9c5qavmeylwx29fcsa5"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDVkNDNGQSBBdmRROXk2\nTkpYNlkxT2xzYWRSbzlXdWM3RFp5eXpVKzFjOHRxNURlRjlNZQpCcFpHWlV6ZGpC\nRkJEbTJNWmU4bmJWS0dOMEF6TnRlUEhPWnE3S1FjRGNrCi0tLSBFcy93UTZoMG9y\nUFRxODNZUVFuMmJZanFSMFZ0dFVHTDljNnd2ZHlyYzhzCqNohDHAmTbzl0NdsWae\n+VIT7zM3D0fUxuWY6sxIs2FIP6dQ1cwppc9pChKto/gzfmPbTy+5yGvyB7YUa9Bn\nc0A=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qvkcdmncywzgx4vvhmel4zv8cx3zzgmyx2rzvn9w6u8d95k3qatzqcrm7kj"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG90MTY4QSBBMDVYR2hr\neE1YUHNrRVo0bGxESURxTU5TaXdJOVFoenVweUMweHZXeFhmWApMaklWMGllOU4v\nbWhRUHVLN2wxd0hBMHVtL0xsNzkrL2x2UVNKWUFDSzg0Ci0tLSB0MldFL1dIdWd4\nQ2RvOG5wWmFvSHRGbG9mQUhiN1JXOUtQSU1DZDVCcDBFCuh2m5TCvzaemB8b6FIJ\n0t+i9fcQDH0T6S5K+4ZVTNAcipt4eSw0iuX5CzR1RFPmSyq3sO7i6HfZB/PTg1xi\nJ9A=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qdpmtxksz55pzfaju625atdyhtksvsclmxhuqqux6s352wq43ge0cg0cw26"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdEYrMGFmNm9BNkszbUIx\naXB1WEd2Tzg2MkgvUjk3VUFQTE9uQW5PR0JFCjlUcFl4Sy9KRVhMZWp4cWdZU0dE\ncERQc2Y3cGw1eG1GeVJ4UGFqTDhzdmMKLS0tIDhhUjhjeW9BNlRUY3Bwc0JGUDNk\nZ2ovMXkzcnNuOXM2dEJqbUFWOExGalkK6DZ9cEHxOdtXMeiow8sMwTUOnZSC5YNL\n50vNNKPYOBdL6CeVxMnXM4IiAVAyE5ZanFdHlHXEV2bd2szgZ8Pwlg==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1dtahzr3uqenkj4gt6p8ranheglmh9nhl9tasyjj8ezm9xzqpx9dqtvaups"
			}
		],
		"lastmodified": "2026-07-30T22:01:58Z",
		"mac": "ENC[AES256_GCM,data:CrH6YPczgl6Pz9iHw2jkAGbv1tfsvGkKGBI2yhECwIn1WqJmZ00H5HiipOwrbVNRR6xg3kBM03F5frw/raacKpj5dX6uylo29HHjYrtKK6OON0lNrd7i8E8GboXohDJARlPkWnH78DrL4iMbbLa9HhG6BvaX6yj73HrEvtT3STc=,iv:eeocNIwI74La0HYJCcQictG2d1Yh6SJ55IH4Y3bFiyc=,tag:1ILCCiN7TCvsOAudC8iUag==,type:str]",
		"version": "3.13.3"
	}
}
