{
	"data": "ENC[AES256_GCM,data:6OdNWbxLm+X+miC0SJeuDDi9faa3yMmUO12Bk5u/XVRWXEYdCQ==,iv:53nQ7+e9zo/19VDTt7d/fZ3oBSedKw/GbG532T9YExs=,tag:BWSkqYqb7WO3N30m/3EXxA==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHJVUlFDQSBBaGpKV3pl\nWlZvMFZ4WWd6aGRHOGVmU0p4aWtBK1JFdGhFS1NJY3NCQWk1MgpqZDdhdjArS2My\nRmp0TlRhR284QlFWM0IxRmQ5ZWw2R3VYdm5ZYVp1T0I4Ci0tLSBZdEc2ZHpXVFZo\nbENheHdxSUo5SDh6VUtxaGlXRm5NMjlnSmV6UGtaUjgwCpcirv2Qys1mjOX54fdJ\nfESl/fnkuqFLstUdyVoigS9HDDE3tZ1lYcjIr4degzwWmO67OvjNthWbeY4i9qSO\nxfk=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qd84d0gr6gw0kdjztwkgk8h2k5f5477c2eng5j3d9c5qavmeylwx29fcsa5"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDVkNDNGQSBBNkRyT2tX\nTjA5L0NNZHE1TWlMZHhmRlpTVGh6ZE9KNkxqb2NhUS9IRWhJaQp6c1ljZk5TRDlj\nejVVQ2duZFZoUnFNbVpMTThPRCtYNnkwNDNXSXI3UW5NCi0tLSBrMG9vUGt0bnhh\nTnlzTi85Sml0U3pLQWhqYXF2ck5qNWlNQ3NsbkxldFJBCtCKMJGZR+KpAGynFxMK\nepZnC7vJK7LUEu0WX6plVgGxJgoPdcUuaqVq8M4FEHyJ5f4hkKyZmaCaRMIeFHan\n2/s=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qvkcdmncywzgx4vvhmel4zv8cx3zzgmyx2rzvn9w6u8d95k3qatzqcrm7kj"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG90MTY4QSBBeDQ1djB6\nb1B1cFJ5Rm92QU1xUkFRYmZ6cldJZStsVzdWTFkzdGJnSjByeQo0WmkvU3VZY3hq\nNmpQTzFPQkNaRHhDMTUyTFNpaVVJNXYzQ3B4SkdXamdBCi0tLSBNN2Y1RkUwbTJD\nSkdrTWhMN0VVZU1vUnlHczlpWmpiTHBQUHh0UGxReFpNCoBrv9PFwF5IIlLyjcJA\nZiKTGhofU+WyXtH8qALmm8o4A18R1KSBXftYMIBm/VnWon6/tq4f/mbXtn7qv5jI\nX2c=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qdpmtxksz55pzfaju625atdyhtksvsclmxhuqqux6s352wq43ge0cg0cw26"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWW84emZuQkdWK3BvdWo3\nbEtCS05hTEUxeThFZG80cDZHcTFCZGVVOVVJCklQWURrKzhXRmZTR0VtVUNKN3I3\ndEt0VTJORFJ2ZUlSaDNDdm9veWRISnMKLS0tIDlGM3dLWUg1SFhLSEt2VDV5Y3VC\nMnBmclVRNURTaGVtMmQ5Z0xKZjFOV28KHOabcIBlYJCOIApEDeH5G96KncSUAvZS\njhMm6ZhQhK6iCZD9gsBNbUd3InpYvXuXSzjcO3ayy3IltqmsxT/ATA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1rq9r6xg57v9v07usktvug8rqv4cvp57qq5gr0yfw23ugxu88rprq75jr9m"
			}
		],
		"lastmodified": "2026-07-19T20:38:20Z",
		"mac": "ENC[AES256_GCM,data:b1CMOnzpIPCfEw1Vqs+rySotjwc/yFXhutFJXz3TTU1Nc/LX+mwR31pXABChrp5KEALm0WkNMJL5VGC5ojAz9RXZq1Lo62jZbCa3CEJD8Xlwd5jLcOZH6BzzMCFUM+GTuZ9hzWCse2ZE33nSAlobva1lk4DATCWNdsjJnLseK+s=,iv:uZwDvJ09DuMP1WYt1ectIVGFALXidCh1AmQZa8oo9CE=,tag:bhGRZwk3PLR+mtlqKD7hHw==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.13.2"
	}
}
